---

- name: Config K8 users
  block:

  - name: Check if admin.conf exist
    stat:
      path: /etc/kubernetes/admin.conf
    register: k8ConfigResult
  
  - name: create k8 home dir
    file:
      path: /home/vagrant/.kube
      state: directory
      owner: vagrant
      group: vagrant  
    
  - name: Copy files to home dir
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant 
      remote_src: yes
    when: k8ConfigResult.stat.exists == true
    run_once: True

  - name: Sync admin.conf between nodes
    synchronize:
      src: /etc/kubernetes/admin.conf
      dest: /etc/kubernetes/admin.conf
    delegate_to: k8boot
    when: k8ConfigResult.stat.exists == false
     
  become: yes
  become_user: root
  