---

- name: Generate token
  block:

  # - name: check if token is created
  #   shell: kubectl get namespaces
  #   register: CREATE_TOKEN
  #   ignore_errors: true

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: JOIN_TOKEN
    # when: CREATE_TOKEN.rc !=1
    run_once: True

  - debug: msg="{{ JOIN_TOKEN.stdout }}"

  - name: Register dummy host with variable
    add_host:
      name: "DUMMY_HOST"
      JOIN_TOKEN_NEW: "{{ JOIN_TOKEN.stdout }}"

  become: yes
  become_user: vagrant