---

- name: Add users to docker group
  block:

    - name: Add users to docker groupe
      user:
        name: "{{ item }}"
        groups: docker
        append: true
      loop:
        - vagrant
      when: "'docker-ce' not in ansible_facts.packages"

  become: yes
  become_user: root