---

- name: Remove and disable swap
  block:

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      loop:
        - swap
        - none
      when: "'docker-ce' not in ansible_facts.packages"

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

  become: yes
  become_user: root
