---
    - hosts: all
      gather_facts: yes
      remote_user: root
      become: yes
      become_user: root
      
      tasks:
                  
      - name: test connection
        ping:
        register: pong

      - debug:
          var: pong.stdout_lines