---
- name: "*** PLAY01 commen K8 config ***"
  hosts: bootstrap, nodes
  vars_files:
    group_vars/all
  remote_user: "$USER"
  gather_facts: yes

  roles:
    - config-apt
    - add-docker
    - add-users-docker
    - remove-swap
    - add-kubernetes
    

  handlers:
    - name: docker status
      service: name=docker state=started

- name: "*** PLAY02 Config user, add network and create K8 token "
  hosts: bootstrap

  roles:
    - init-kubernetes
    - config-k8-users
    - add-calico
    - create-join-token

- name: "*** PLAY3 Join nodes to K8 cluster *** "
  hosts: nodes
  
  roles:
    - add-join-token